name: Publish Python Package to PyPI

on:
  # Manually run using: gh workflow run publish.yml --ref main
  workflow_dispatch:  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"  # Use default Python version

      # Install build dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Build the package
      - name: Build the package
        run: |
          python -m build

      # Publish to PyPI using Trusted Publishing
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
